### ISSUE TITLE
login is not working

### ISSUE THREAD

**Issue by sarawasim** [sarawasim/contendr#10]
I tried to login using both mongo and github but they stopped working. I am not too sure what the issue is. The error I get is "Error connecting to MongoDB"

<img width="891" alt="Screen_Shot_2021-04-29_at_4 24 32_AM" src="https://user-images.githubusercontent.com/71532511/116543866-4246bd80-a8a3-11eb-8cad-baa88043976f.png">

**Comment by Ovillena** [comment]
resolved by creating local MongoDB and connecting to cloud atlas mongo
